// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go.orx.me/apps/hyper-sync/internal/dao"
	"go.orx.me/apps/hyper-sync/internal/service"
)

// Injectors from wire.go:

func NewSyncService() (*service.SyncService, error) {
	client, err := dao.NewMongoClient()
	if err != nil {
		return nil, err
	}
	postDao := dao.NewMongoDAO(client)
	syncService, err := service.NewSyncService(postDao)
	if err != nil {
		return nil, err
	}
	return syncService, nil
}
