// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go.orx.me/apps/hyper-sync/internal/dao"
	"go.orx.me/apps/hyper-sync/internal/service"
)

// Injectors from wire.go:

func NewSyncService(mainSocial string, socials []string) (*service.SyncService, error) {
	client := dao.NewMongoClient()
	postDao := dao.NewPostDao(client)
	socialConfigDao := dao.NewSocialConfigDao(client)
	threadsConfigAdapter := dao.NewThreadsConfigAdapter(socialConfigDao)
	syncCursorDao := dao.NewSyncCursorDao(client)
	socialService, err := service.NewSocialService(threadsConfigAdapter, syncCursorDao)
	if err != nil {
		return nil, err
	}
	redisClient := dao.NewRedisClient()
	redislockClient := dao.NewLocker(redisClient)
	syncService, err := service.NewSyncService(postDao, socialService, redislockClient, mainSocial, socials)
	if err != nil {
		return nil, err
	}
	return syncService, nil
}

func NewSchedulerService() (*service.SchedulerService, error) {
	client := dao.NewMongoClient()
	socialConfigDao := dao.NewSocialConfigDao(client)
	threadsConfigAdapter := dao.NewThreadsConfigAdapter(socialConfigDao)
	syncCursorDao := dao.NewSyncCursorDao(client)
	socialService, err := service.NewSocialService(threadsConfigAdapter, syncCursorDao)
	if err != nil {
		return nil, err
	}
	redisClient := dao.NewRedisClient()
	redislockClient := dao.NewLocker(redisClient)
	schedulerService := service.NewSchedulerService(socialService, redislockClient, threadsConfigAdapter)
	return schedulerService, nil
}

func NewSocialServiceOnly() (*service.SocialService, error) {
	client := dao.NewMongoClient()
	socialConfigDao := dao.NewSocialConfigDao(client)
	threadsConfigAdapter := dao.NewThreadsConfigAdapter(socialConfigDao)
	syncCursorDao := dao.NewSyncCursorDao(client)
	socialService, err := service.NewSocialService(threadsConfigAdapter, syncCursorDao)
	if err != nil {
		return nil, err
	}
	return socialService, nil
}

func NewMongoDAO() *dao.MongoDAO {
	client := dao.NewMongoClient()
	mongoDAO := dao.NewMongoDAO(client)
	return mongoDAO
}
