// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go.orx.me/apps/hyper-sync/internal/dao"
	"go.orx.me/apps/hyper-sync/internal/service"
)

// Injectors from wire.go:

func NewSyncService(mainSocail string, socials []string) (*service.SyncService, error) {
	client := dao.NewMongoClient()
	postDao := dao.NewMongoDAO(client)
	socialService, err := service.NewSocialService()
	if err != nil {
		return nil, err
	}
	redisClient := dao.NewRedisClient()
	redislockClient := dao.NewLocker(redisClient)
	syncService, err := service.NewSyncService(postDao, socialService, redislockClient, mainSocail, socials)
	if err != nil {
		return nil, err
	}
	return syncService, nil
}
