// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/post.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.orx.me/apps/hyper-sync/pkg/proto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PostServiceName is the fully-qualified name of the PostService service.
	PostServiceName = "api.v1.PostService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PostServiceCreatePostProcedure is the fully-qualified name of the PostService's CreatePost RPC.
	PostServiceCreatePostProcedure = "/api.v1.PostService/CreatePost"
	// PostServiceUpdatePostProcedure is the fully-qualified name of the PostService's UpdatePost RPC.
	PostServiceUpdatePostProcedure = "/api.v1.PostService/UpdatePost"
	// PostServiceGetPostProcedure is the fully-qualified name of the PostService's GetPost RPC.
	PostServiceGetPostProcedure = "/api.v1.PostService/GetPost"
	// PostServiceListPostsProcedure is the fully-qualified name of the PostService's ListPosts RPC.
	PostServiceListPostsProcedure = "/api.v1.PostService/ListPosts"
	// PostServiceDeletePostProcedure is the fully-qualified name of the PostService's DeletePost RPC.
	PostServiceDeletePostProcedure = "/api.v1.PostService/DeletePost"
	// PostServicePublishPostProcedure is the fully-qualified name of the PostService's PublishPost RPC.
	PostServicePublishPostProcedure = "/api.v1.PostService/PublishPost"
)

// PostServiceClient is a client for the api.v1.PostService service.
type PostServiceClient interface {
	// CreatePost creates a new post
	CreatePost(context.Context, *connect.Request[v1.CreatePostRequest]) (*connect.Response[v1.CreatePostResponse], error)
	// UpdatePost updates an existing post
	UpdatePost(context.Context, *connect.Request[v1.UpdatePostRequest]) (*connect.Response[v1.UpdatePostResponse], error)
	// GetPost retrieves a single post by ID
	GetPost(context.Context, *connect.Request[v1.GetPostRequest]) (*connect.Response[v1.GetPostResponse], error)
	// ListPosts retrieves a list of posts with optional filtering
	ListPosts(context.Context, *connect.Request[v1.ListPostsRequest]) (*connect.Response[v1.ListPostsResponse], error)
	// DeletePost deletes a post by ID
	DeletePost(context.Context, *connect.Request[v1.DeletePostRequest]) (*connect.Response[v1.DeletePostResponse], error)
	// PublishPost publishes a draft or scheduled post
	PublishPost(context.Context, *connect.Request[v1.PublishPostRequest]) (*connect.Response[v1.PublishPostResponse], error)
}

// NewPostServiceClient constructs a client for the api.v1.PostService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPostServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PostServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	postServiceMethods := v1.File_api_v1_post_proto.Services().ByName("PostService").Methods()
	return &postServiceClient{
		createPost: connect.NewClient[v1.CreatePostRequest, v1.CreatePostResponse](
			httpClient,
			baseURL+PostServiceCreatePostProcedure,
			connect.WithSchema(postServiceMethods.ByName("CreatePost")),
			connect.WithClientOptions(opts...),
		),
		updatePost: connect.NewClient[v1.UpdatePostRequest, v1.UpdatePostResponse](
			httpClient,
			baseURL+PostServiceUpdatePostProcedure,
			connect.WithSchema(postServiceMethods.ByName("UpdatePost")),
			connect.WithClientOptions(opts...),
		),
		getPost: connect.NewClient[v1.GetPostRequest, v1.GetPostResponse](
			httpClient,
			baseURL+PostServiceGetPostProcedure,
			connect.WithSchema(postServiceMethods.ByName("GetPost")),
			connect.WithClientOptions(opts...),
		),
		listPosts: connect.NewClient[v1.ListPostsRequest, v1.ListPostsResponse](
			httpClient,
			baseURL+PostServiceListPostsProcedure,
			connect.WithSchema(postServiceMethods.ByName("ListPosts")),
			connect.WithClientOptions(opts...),
		),
		deletePost: connect.NewClient[v1.DeletePostRequest, v1.DeletePostResponse](
			httpClient,
			baseURL+PostServiceDeletePostProcedure,
			connect.WithSchema(postServiceMethods.ByName("DeletePost")),
			connect.WithClientOptions(opts...),
		),
		publishPost: connect.NewClient[v1.PublishPostRequest, v1.PublishPostResponse](
			httpClient,
			baseURL+PostServicePublishPostProcedure,
			connect.WithSchema(postServiceMethods.ByName("PublishPost")),
			connect.WithClientOptions(opts...),
		),
	}
}

// postServiceClient implements PostServiceClient.
type postServiceClient struct {
	createPost  *connect.Client[v1.CreatePostRequest, v1.CreatePostResponse]
	updatePost  *connect.Client[v1.UpdatePostRequest, v1.UpdatePostResponse]
	getPost     *connect.Client[v1.GetPostRequest, v1.GetPostResponse]
	listPosts   *connect.Client[v1.ListPostsRequest, v1.ListPostsResponse]
	deletePost  *connect.Client[v1.DeletePostRequest, v1.DeletePostResponse]
	publishPost *connect.Client[v1.PublishPostRequest, v1.PublishPostResponse]
}

// CreatePost calls api.v1.PostService.CreatePost.
func (c *postServiceClient) CreatePost(ctx context.Context, req *connect.Request[v1.CreatePostRequest]) (*connect.Response[v1.CreatePostResponse], error) {
	return c.createPost.CallUnary(ctx, req)
}

// UpdatePost calls api.v1.PostService.UpdatePost.
func (c *postServiceClient) UpdatePost(ctx context.Context, req *connect.Request[v1.UpdatePostRequest]) (*connect.Response[v1.UpdatePostResponse], error) {
	return c.updatePost.CallUnary(ctx, req)
}

// GetPost calls api.v1.PostService.GetPost.
func (c *postServiceClient) GetPost(ctx context.Context, req *connect.Request[v1.GetPostRequest]) (*connect.Response[v1.GetPostResponse], error) {
	return c.getPost.CallUnary(ctx, req)
}

// ListPosts calls api.v1.PostService.ListPosts.
func (c *postServiceClient) ListPosts(ctx context.Context, req *connect.Request[v1.ListPostsRequest]) (*connect.Response[v1.ListPostsResponse], error) {
	return c.listPosts.CallUnary(ctx, req)
}

// DeletePost calls api.v1.PostService.DeletePost.
func (c *postServiceClient) DeletePost(ctx context.Context, req *connect.Request[v1.DeletePostRequest]) (*connect.Response[v1.DeletePostResponse], error) {
	return c.deletePost.CallUnary(ctx, req)
}

// PublishPost calls api.v1.PostService.PublishPost.
func (c *postServiceClient) PublishPost(ctx context.Context, req *connect.Request[v1.PublishPostRequest]) (*connect.Response[v1.PublishPostResponse], error) {
	return c.publishPost.CallUnary(ctx, req)
}

// PostServiceHandler is an implementation of the api.v1.PostService service.
type PostServiceHandler interface {
	// CreatePost creates a new post
	CreatePost(context.Context, *connect.Request[v1.CreatePostRequest]) (*connect.Response[v1.CreatePostResponse], error)
	// UpdatePost updates an existing post
	UpdatePost(context.Context, *connect.Request[v1.UpdatePostRequest]) (*connect.Response[v1.UpdatePostResponse], error)
	// GetPost retrieves a single post by ID
	GetPost(context.Context, *connect.Request[v1.GetPostRequest]) (*connect.Response[v1.GetPostResponse], error)
	// ListPosts retrieves a list of posts with optional filtering
	ListPosts(context.Context, *connect.Request[v1.ListPostsRequest]) (*connect.Response[v1.ListPostsResponse], error)
	// DeletePost deletes a post by ID
	DeletePost(context.Context, *connect.Request[v1.DeletePostRequest]) (*connect.Response[v1.DeletePostResponse], error)
	// PublishPost publishes a draft or scheduled post
	PublishPost(context.Context, *connect.Request[v1.PublishPostRequest]) (*connect.Response[v1.PublishPostResponse], error)
}

// NewPostServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPostServiceHandler(svc PostServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	postServiceMethods := v1.File_api_v1_post_proto.Services().ByName("PostService").Methods()
	postServiceCreatePostHandler := connect.NewUnaryHandler(
		PostServiceCreatePostProcedure,
		svc.CreatePost,
		connect.WithSchema(postServiceMethods.ByName("CreatePost")),
		connect.WithHandlerOptions(opts...),
	)
	postServiceUpdatePostHandler := connect.NewUnaryHandler(
		PostServiceUpdatePostProcedure,
		svc.UpdatePost,
		connect.WithSchema(postServiceMethods.ByName("UpdatePost")),
		connect.WithHandlerOptions(opts...),
	)
	postServiceGetPostHandler := connect.NewUnaryHandler(
		PostServiceGetPostProcedure,
		svc.GetPost,
		connect.WithSchema(postServiceMethods.ByName("GetPost")),
		connect.WithHandlerOptions(opts...),
	)
	postServiceListPostsHandler := connect.NewUnaryHandler(
		PostServiceListPostsProcedure,
		svc.ListPosts,
		connect.WithSchema(postServiceMethods.ByName("ListPosts")),
		connect.WithHandlerOptions(opts...),
	)
	postServiceDeletePostHandler := connect.NewUnaryHandler(
		PostServiceDeletePostProcedure,
		svc.DeletePost,
		connect.WithSchema(postServiceMethods.ByName("DeletePost")),
		connect.WithHandlerOptions(opts...),
	)
	postServicePublishPostHandler := connect.NewUnaryHandler(
		PostServicePublishPostProcedure,
		svc.PublishPost,
		connect.WithSchema(postServiceMethods.ByName("PublishPost")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.PostService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PostServiceCreatePostProcedure:
			postServiceCreatePostHandler.ServeHTTP(w, r)
		case PostServiceUpdatePostProcedure:
			postServiceUpdatePostHandler.ServeHTTP(w, r)
		case PostServiceGetPostProcedure:
			postServiceGetPostHandler.ServeHTTP(w, r)
		case PostServiceListPostsProcedure:
			postServiceListPostsHandler.ServeHTTP(w, r)
		case PostServiceDeletePostProcedure:
			postServiceDeletePostHandler.ServeHTTP(w, r)
		case PostServicePublishPostProcedure:
			postServicePublishPostHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPostServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPostServiceHandler struct{}

func (UnimplementedPostServiceHandler) CreatePost(context.Context, *connect.Request[v1.CreatePostRequest]) (*connect.Response[v1.CreatePostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PostService.CreatePost is not implemented"))
}

func (UnimplementedPostServiceHandler) UpdatePost(context.Context, *connect.Request[v1.UpdatePostRequest]) (*connect.Response[v1.UpdatePostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PostService.UpdatePost is not implemented"))
}

func (UnimplementedPostServiceHandler) GetPost(context.Context, *connect.Request[v1.GetPostRequest]) (*connect.Response[v1.GetPostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PostService.GetPost is not implemented"))
}

func (UnimplementedPostServiceHandler) ListPosts(context.Context, *connect.Request[v1.ListPostsRequest]) (*connect.Response[v1.ListPostsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PostService.ListPosts is not implemented"))
}

func (UnimplementedPostServiceHandler) DeletePost(context.Context, *connect.Request[v1.DeletePostRequest]) (*connect.Response[v1.DeletePostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PostService.DeletePost is not implemented"))
}

func (UnimplementedPostServiceHandler) PublishPost(context.Context, *connect.Request[v1.PublishPostRequest]) (*connect.Response[v1.PublishPostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.PostService.PublishPost is not implemented"))
}
