// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: api/v1/hyper.proto

package v1

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ==========================
// HyperSyncService Interface
// ==========================

type HyperSyncService interface {
	// ListPosts retrieves a list of posts with optional filtering
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)

	// GetPost retrieves a single post by ID
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)

	// CreatePost creates a new post
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)

	// DeletePost deletes a post by ID
	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
}

// ================================
// HyperSyncService Protobuf Client
// ================================

type hyperSyncServiceProtobufClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewHyperSyncServiceProtobufClient creates a Protobuf client that implements the HyperSyncService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewHyperSyncServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) HyperSyncService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "api.v1", "HyperSyncService")
	urls := [4]string{
		serviceURL + "ListPosts",
		serviceURL + "GetPost",
		serviceURL + "CreatePost",
		serviceURL + "DeletePost",
	}

	return &hyperSyncServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *hyperSyncServiceProtobufClient) ListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	caller := c.callListPosts
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return c.callListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceProtobufClient) callListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *hyperSyncServiceProtobufClient) GetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	caller := c.callGetPost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return c.callGetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceProtobufClient) callGetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *hyperSyncServiceProtobufClient) CreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	caller := c.callCreatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return c.callCreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceProtobufClient) callCreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *hyperSyncServiceProtobufClient) DeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	caller := c.callDeletePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return c.callDeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceProtobufClient) callDeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ============================
// HyperSyncService JSON Client
// ============================

type hyperSyncServiceJSONClient struct {
	client      HTTPClient
	urls        [4]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewHyperSyncServiceJSONClient creates a JSON client that implements the HyperSyncService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewHyperSyncServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) HyperSyncService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "api.v1", "HyperSyncService")
	urls := [4]string{
		serviceURL + "ListPosts",
		serviceURL + "GetPost",
		serviceURL + "CreatePost",
		serviceURL + "DeletePost",
	}

	return &hyperSyncServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *hyperSyncServiceJSONClient) ListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	caller := c.callListPosts
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return c.callListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceJSONClient) callListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *hyperSyncServiceJSONClient) GetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	caller := c.callGetPost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return c.callGetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceJSONClient) callGetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *hyperSyncServiceJSONClient) CreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	caller := c.callCreatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return c.callCreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceJSONClient) callCreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *hyperSyncServiceJSONClient) DeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	caller := c.callDeletePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return c.callDeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *hyperSyncServiceJSONClient) callDeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===============================
// HyperSyncService Server Handler
// ===============================

type hyperSyncServiceServer struct {
	HyperSyncService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewHyperSyncServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewHyperSyncServiceServer(svc HyperSyncService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &hyperSyncServiceServer{
		HyperSyncService: svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *hyperSyncServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *hyperSyncServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// HyperSyncServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const HyperSyncServicePathPrefix = "/twirp/api.v1.HyperSyncService/"

func (s *hyperSyncServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "HyperSyncService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "api.v1.HyperSyncService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "ListPosts":
		s.serveListPosts(ctx, resp, req)
		return
	case "GetPost":
		s.serveGetPost(ctx, resp, req)
		return
	case "CreatePost":
		s.serveCreatePost(ctx, resp, req)
		return
	case "DeletePost":
		s.serveDeletePost(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *hyperSyncServiceServer) serveListPosts(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListPostsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListPostsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *hyperSyncServiceServer) serveListPostsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListPostsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.HyperSyncService.ListPosts
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return s.HyperSyncService.ListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListPostsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListPostsResponse and nil error while calling ListPosts. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveListPostsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListPostsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.HyperSyncService.ListPosts
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return s.HyperSyncService.ListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListPostsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListPostsResponse and nil error while calling ListPosts. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveGetPost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetPostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetPostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *hyperSyncServiceServer) serveGetPostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetPostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.HyperSyncService.GetPost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return s.HyperSyncService.GetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPostResponse and nil error while calling GetPost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveGetPostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetPostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.HyperSyncService.GetPost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return s.HyperSyncService.GetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPostResponse and nil error while calling GetPost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveCreatePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreatePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreatePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *hyperSyncServiceServer) serveCreatePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreatePostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.HyperSyncService.CreatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return s.HyperSyncService.CreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreatePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreatePostResponse and nil error while calling CreatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveCreatePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreatePostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.HyperSyncService.CreatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return s.HyperSyncService.CreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreatePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreatePostResponse and nil error while calling CreatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveDeletePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeletePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeletePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *hyperSyncServiceServer) serveDeletePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeletePostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.HyperSyncService.DeletePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return s.HyperSyncService.DeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeletePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeletePostResponse and nil error while calling DeletePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) serveDeletePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeletePostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.HyperSyncService.DeletePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return s.HyperSyncService.DeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeletePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeletePostResponse and nil error while calling DeletePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *hyperSyncServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *hyperSyncServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *hyperSyncServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "api.v1", "HyperSyncService")
}

var twirpFileDescriptor1 = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5d, 0x6e, 0xdb, 0x38,
	0x10, 0x8e, 0x2c, 0xff, 0x8e, 0x83, 0x38, 0x26, 0x82, 0x8d, 0xe2, 0x05, 0x36, 0x8e, 0x76, 0x81,
	0x35, 0x8a, 0x46, 0x42, 0x9c, 0x87, 0xb4, 0x45, 0x5f, 0x92, 0x34, 0x68, 0x0d, 0xb4, 0x40, 0xa0,
	0xf4, 0xa9, 0x7d, 0x30, 0x14, 0x89, 0x71, 0x89, 0xc8, 0xa2, 0x4a, 0x52, 0x46, 0x7d, 0x80, 0x5e,
	0xa4, 0x07, 0xe9, 0x0d, 0x7a, 0x99, 0x9e, 0xa0, 0x20, 0x29, 0xd9, 0xb2, 0xe2, 0xfc, 0xbc, 0x69,
	0x66, 0xbe, 0x19, 0x0e, 0xbf, 0x6f, 0x46, 0x04, 0xe4, 0x27, 0xc4, 0x9d, 0x1d, 0xb9, 0x5f, 0xe6,
	0x09, 0x66, 0x4e, 0xc2, 0xa8, 0xa0, 0xa8, 0xee, 0x27, 0xc4, 0x99, 0x1d, 0xf5, 0xf6, 0x27, 0x94,
	0x4e, 0x22, 0xec, 0x2a, 0xef, 0x75, 0x7a, 0xe3, 0x0a, 0x32, 0xc5, 0x5c, 0xf8, 0xd3, 0x44, 0x03,
	0xed, 0xdf, 0x26, 0x54, 0x2f, 0x29, 0x17, 0x68, 0x0b, 0x2a, 0x24, 0xb4, 0x8c, 0xbe, 0x31, 0x68,
	0x79, 0x15, 0x12, 0xa2, 0x5d, 0x68, 0xa4, 0x1c, 0xb3, 0x31, 0x09, 0xad, 0x8a, 0x72, 0xd6, 0xa5,
	0x39, 0x0a, 0x91, 0x05, 0x8d, 0x80, 0xc6, 0x02, 0xc7, 0xc2, 0x32, 0x55, 0x20, 0x37, 0xd1, 0x3f,
	0x00, 0x33, 0xc2, 0xc9, 0x35, 0x89, 0x88, 0x98, 0x5b, 0x55, 0x15, 0x2c, 0x78, 0xd0, 0xff, 0xd0,
	0xe1, 0x34, 0x65, 0x01, 0x1e, 0x27, 0x91, 0x2f, 0x6e, 0x28, 0x9b, 0x5a, 0x35, 0x05, 0xda, 0xd2,
	0xee, 0xcb, 0xcc, 0x8b, 0xf6, 0xa1, 0x4d, 0x19, 0x99, 0x90, 0xd8, 0x8f, 0xe4, 0xf9, 0x75, 0x5d,
	0x29, 0x77, 0x8d, 0x42, 0xf4, 0x37, 0xb4, 0xa6, 0x38, 0x24, 0xfe, 0x98, 0x84, 0xdc, 0x6a, 0xf4,
	0xcd, 0x41, 0xcb, 0x6b, 0x2a, 0xc7, 0x28, 0xe4, 0xe8, 0x25, 0x40, 0xc0, 0xb0, 0x2f, 0x70, 0x38,
	0xf6, 0x85, 0xd5, 0xec, 0x1b, 0x83, 0xf6, 0xb0, 0xe7, 0x68, 0x22, 0x9c, 0x9c, 0x08, 0xe7, 0x63,
	0x4e, 0x84, 0xd7, 0xca, 0xd0, 0xa7, 0x42, 0xa6, 0xa6, 0x49, 0x98, 0xa7, 0xb6, 0x1e, 0x4f, 0xcd,
	0xd0, 0xa7, 0x02, 0x7d, 0x80, 0x6e, 0xc0, 0x28, 0xe7, 0xe3, 0x84, 0x72, 0x31, 0xe6, 0xc2, 0x17,
	0x29, 0xb7, 0xa0, 0x6f, 0x0e, 0xda, 0xc3, 0x03, 0x47, 0xab, 0xe1, 0x48, 0xa2, 0x9d, 0x73, 0x89,
	0x92, 0x5f, 0x57, 0x0a, 0x73, 0x11, 0x0b, 0x36, 0xf7, 0x3a, 0xc1, 0xaa, 0xb7, 0xf7, 0x19, 0x76,
	0xd6, 0x01, 0xd1, 0x36, 0x98, 0xb7, 0x78, 0x9e, 0xe9, 0x24, 0x3f, 0xd1, 0x21, 0xd4, 0x66, 0x7e,
	0x94, 0x62, 0x25, 0x53, 0x7b, 0xb8, 0x9b, 0x1f, 0x56, 0x4a, 0xf7, 0x34, 0xea, 0x55, 0xe5, 0x85,
	0x61, 0xff, 0x34, 0xa0, 0x53, 0x0a, 0x4b, 0x59, 0x79, 0x1a, 0x04, 0x98, 0x73, 0x55, 0xbc, 0xe9,
	0xe5, 0x26, 0xda, 0x81, 0x1a, 0x66, 0x8c, 0xb2, 0x6c, 0x0e, 0xb4, 0x21, 0x35, 0xca, 0x55, 0x94,
	0x1a, 0xe9, 0x51, 0x80, 0xdc, 0x35, 0x0a, 0xd1, 0x01, 0x6c, 0x2e, 0x09, 0xc1, 0xa1, 0x9a, 0x87,
	0xa6, 0xd7, 0x5e, 0x5c, 0x14, 0x87, 0xe8, 0x04, 0x5a, 0x3a, 0x28, 0xd9, 0xae, 0x3d, 0xca, 0x76,
	0x53, 0x83, 0x4f, 0x85, 0xfd, 0xdd, 0x80, 0xed, 0xf7, 0x84, 0x0b, 0x59, 0x87, 0x7b, 0xf8, 0x6b,
	0x8a, 0xb9, 0x90, 0x7d, 0x46, 0x64, 0x4a, 0x84, 0xea, 0xdf, 0xf4, 0xb4, 0x81, 0x10, 0x54, 0xf9,
	0x2d, 0x49, 0x54, 0xf3, 0xa6, 0xa7, 0xbe, 0xd7, 0x0d, 0xa2, 0xb9, 0x76, 0x10, 0x1f, 0x99, 0x68,
	0xfb, 0x04, 0xba, 0x85, 0x36, 0x78, 0x42, 0x63, 0x8e, 0x91, 0x0d, 0x35, 0xd9, 0xa8, 0xe4, 0x51,
	0xaa, 0xbf, 0x59, 0x54, 0xdf, 0xd3, 0x21, 0xbb, 0x0f, 0x5b, 0x6f, 0xb1, 0xca, 0xcb, 0xbb, 0x2f,
	0xed, 0x9f, 0x7d, 0x0c, 0x9d, 0x05, 0x22, 0x2b, 0xdc, 0x87, 0xaa, 0xcc, 0x56, 0xa0, 0x72, 0x5d,
	0x15, 0xb1, 0x7f, 0x19, 0xd0, 0x3d, 0x57, 0xd3, 0x5c, 0x2c, 0x5d, 0x58, 0x65, 0xe3, 0xbe, 0x55,
	0xae, 0x3c, 0xb4, 0xca, 0xe6, 0x53, 0x56, 0xb9, 0xfa, 0x94, 0x55, 0xae, 0x3d, 0xbc, 0xca, 0xf5,
	0xd5, 0x55, 0xb6, 0xff, 0x03, 0x54, 0xbc, 0x4e, 0xc6, 0x43, 0x99, 0xaa, 0x7f, 0xa1, 0xfb, 0x06,
	0x47, 0x78, 0xf5, 0xd2, 0x65, 0x90, 0x03, 0xa8, 0x08, 0xca, 0x4a, 0xdd, 0x3b, 0xf5, 0xc3, 0x1f,
	0x15, 0xd8, 0x7e, 0x27, 0xff, 0xa8, 0x57, 0xf3, 0x38, 0xb8, 0xc2, 0x6c, 0x46, 0x02, 0x8c, 0xce,
	0xa0, 0xb5, 0xd0, 0x1b, 0x59, 0xb9, 0x00, 0xe5, 0x49, 0xec, 0xed, 0xad, 0x89, 0xe8, 0x03, 0xed,
	0x0d, 0xf4, 0x1a, 0x1a, 0x99, 0xb0, 0xe8, 0xaf, 0x1c, 0xb7, 0x3a, 0x0b, 0xbd, 0xdd, 0x3b, 0xfe,
	0x45, 0xf6, 0x05, 0xc0, 0x92, 0x11, 0xb4, 0xb7, 0x5c, 0xf6, 0x92, 0xe8, 0xbd, 0xde, 0xba, 0x50,
	0xb1, 0xcc, 0x92, 0x8d, 0x65, 0x99, 0x3b, 0x34, 0x2e, 0xcb, 0xdc, 0x25, 0xcf, 0xde, 0x38, 0x7b,
	0xfe, 0xe9, 0xd9, 0x84, 0x3a, 0x94, 0x7d, 0x73, 0xa6, 0xd8, 0xf5, 0x93, 0x84, 0xeb, 0x47, 0xe8,
	0x90, 0xcf, 0xe3, 0xc0, 0x4d, 0x6e, 0x27, 0xfa, 0xdd, 0x71, 0xf5, 0x03, 0x75, 0x5d, 0x57, 0xd6,
	0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x2a, 0x1e, 0x6a, 0xb1, 0x06, 0x00, 0x00,
}
