// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: api/v1/media.proto

package v1

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// MediaService Interface
// ======================

type MediaService interface {
	GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error)

	ListMedia(context.Context, *ListMediaRequest) (*ListMediaResponse, error)

	DeleteMedia(context.Context, *DeleteMediaRequest) (*DeleteMediaResponse, error)
}

// ============================
// MediaService Protobuf Client
// ============================

type mediaServiceProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewMediaServiceProtobufClient creates a Protobuf client that implements the MediaService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewMediaServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) MediaService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "api.v1", "MediaService")
	urls := [3]string{
		serviceURL + "GetMedia",
		serviceURL + "ListMedia",
		serviceURL + "DeleteMedia",
	}

	return &mediaServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *mediaServiceProtobufClient) GetMedia(ctx context.Context, in *GetMediaRequest) (*GetMediaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithMethodName(ctx, "GetMedia")
	caller := c.callGetMedia
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetMediaRequest) (*GetMediaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMediaRequest) when calling interceptor")
					}
					return c.callGetMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *mediaServiceProtobufClient) callGetMedia(ctx context.Context, in *GetMediaRequest) (*GetMediaResponse, error) {
	out := new(GetMediaResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *mediaServiceProtobufClient) ListMedia(ctx context.Context, in *ListMediaRequest) (*ListMediaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithMethodName(ctx, "ListMedia")
	caller := c.callListMedia
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListMediaRequest) (*ListMediaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListMediaRequest) when calling interceptor")
					}
					return c.callListMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *mediaServiceProtobufClient) callListMedia(ctx context.Context, in *ListMediaRequest) (*ListMediaResponse, error) {
	out := new(ListMediaResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *mediaServiceProtobufClient) DeleteMedia(ctx context.Context, in *DeleteMediaRequest) (*DeleteMediaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteMedia")
	caller := c.callDeleteMedia
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteMediaRequest) (*DeleteMediaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteMediaRequest) when calling interceptor")
					}
					return c.callDeleteMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *mediaServiceProtobufClient) callDeleteMedia(ctx context.Context, in *DeleteMediaRequest) (*DeleteMediaResponse, error) {
	out := new(DeleteMediaResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// MediaService JSON Client
// ========================

type mediaServiceJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewMediaServiceJSONClient creates a JSON client that implements the MediaService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewMediaServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) MediaService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "api.v1", "MediaService")
	urls := [3]string{
		serviceURL + "GetMedia",
		serviceURL + "ListMedia",
		serviceURL + "DeleteMedia",
	}

	return &mediaServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *mediaServiceJSONClient) GetMedia(ctx context.Context, in *GetMediaRequest) (*GetMediaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithMethodName(ctx, "GetMedia")
	caller := c.callGetMedia
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetMediaRequest) (*GetMediaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMediaRequest) when calling interceptor")
					}
					return c.callGetMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *mediaServiceJSONClient) callGetMedia(ctx context.Context, in *GetMediaRequest) (*GetMediaResponse, error) {
	out := new(GetMediaResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *mediaServiceJSONClient) ListMedia(ctx context.Context, in *ListMediaRequest) (*ListMediaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithMethodName(ctx, "ListMedia")
	caller := c.callListMedia
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListMediaRequest) (*ListMediaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListMediaRequest) when calling interceptor")
					}
					return c.callListMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *mediaServiceJSONClient) callListMedia(ctx context.Context, in *ListMediaRequest) (*ListMediaResponse, error) {
	out := new(ListMediaResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *mediaServiceJSONClient) DeleteMedia(ctx context.Context, in *DeleteMediaRequest) (*DeleteMediaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteMedia")
	caller := c.callDeleteMedia
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteMediaRequest) (*DeleteMediaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteMediaRequest) when calling interceptor")
					}
					return c.callDeleteMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *mediaServiceJSONClient) callDeleteMedia(ctx context.Context, in *DeleteMediaRequest) (*DeleteMediaResponse, error) {
	out := new(DeleteMediaResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// MediaService Server Handler
// ===========================

type mediaServiceServer struct {
	MediaService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewMediaServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewMediaServiceServer(svc MediaService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &mediaServiceServer{
		MediaService:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *mediaServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *mediaServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// MediaServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const MediaServicePathPrefix = "/twirp/api.v1.MediaService/"

func (s *mediaServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "MediaService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "api.v1.MediaService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "GetMedia":
		s.serveGetMedia(ctx, resp, req)
		return
	case "ListMedia":
		s.serveListMedia(ctx, resp, req)
		return
	case "DeleteMedia":
		s.serveDeleteMedia(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *mediaServiceServer) serveGetMedia(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetMediaJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetMediaProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *mediaServiceServer) serveGetMediaJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetMedia")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetMediaRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.MediaService.GetMedia
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetMediaRequest) (*GetMediaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMediaRequest) when calling interceptor")
					}
					return s.MediaService.GetMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetMediaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetMediaResponse and nil error while calling GetMedia. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *mediaServiceServer) serveGetMediaProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetMedia")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetMediaRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.MediaService.GetMedia
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetMediaRequest) (*GetMediaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetMediaRequest) when calling interceptor")
					}
					return s.MediaService.GetMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetMediaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetMediaResponse and nil error while calling GetMedia. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *mediaServiceServer) serveListMedia(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListMediaJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListMediaProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *mediaServiceServer) serveListMediaJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListMedia")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListMediaRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.MediaService.ListMedia
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListMediaRequest) (*ListMediaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListMediaRequest) when calling interceptor")
					}
					return s.MediaService.ListMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListMediaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListMediaResponse and nil error while calling ListMedia. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *mediaServiceServer) serveListMediaProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListMedia")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListMediaRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.MediaService.ListMedia
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListMediaRequest) (*ListMediaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListMediaRequest) when calling interceptor")
					}
					return s.MediaService.ListMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListMediaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListMediaResponse and nil error while calling ListMedia. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *mediaServiceServer) serveDeleteMedia(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteMediaJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteMediaProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *mediaServiceServer) serveDeleteMediaJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteMedia")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteMediaRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.MediaService.DeleteMedia
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteMediaRequest) (*DeleteMediaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteMediaRequest) when calling interceptor")
					}
					return s.MediaService.DeleteMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteMediaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteMediaResponse and nil error while calling DeleteMedia. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *mediaServiceServer) serveDeleteMediaProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteMedia")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteMediaRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.MediaService.DeleteMedia
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteMediaRequest) (*DeleteMediaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteMediaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteMediaRequest) when calling interceptor")
					}
					return s.MediaService.DeleteMedia(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeleteMediaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeleteMediaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeleteMediaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteMediaResponse and nil error while calling DeleteMedia. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *mediaServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *mediaServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *mediaServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "api.v1", "MediaService")
}

var twirpFileDescriptor1 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcf, 0x6f, 0xd3, 0x30,
	0x18, 0x25, 0xed, 0x52, 0x96, 0xaf, 0x03, 0x3a, 0x03, 0x5a, 0xc8, 0x84, 0xe8, 0x02, 0x87, 0x8a,
	0x1f, 0x8e, 0x56, 0x0e, 0x88, 0x13, 0xa2, 0x20, 0xe0, 0x00, 0x1c, 0xb2, 0x71, 0xe1, 0x12, 0xb9,
	0xc9, 0xb7, 0x60, 0x91, 0xc4, 0x26, 0x76, 0x2b, 0xb2, 0x3f, 0x15, 0x89, 0xff, 0x05, 0xc5, 0x6e,
	0xba, 0xad, 0xab, 0xb8, 0xd9, 0xef, 0x3d, 0xbf, 0xcf, 0xef, 0x49, 0x1f, 0x10, 0x26, 0x79, 0xb4,
	0x3c, 0x8e, 0x4a, 0xcc, 0x38, 0xa3, 0xb2, 0x16, 0x5a, 0x90, 0x01, 0x93, 0x9c, 0x2e, 0x8f, 0x83,
	0x47, 0xb9, 0x10, 0x79, 0x81, 0x91, 0x41, 0xe7, 0x8b, 0xb3, 0x48, 0xf3, 0x12, 0x95, 0x66, 0xa5,
	0xb4, 0xc2, 0xf0, 0x8f, 0x03, 0xee, 0x97, 0xf6, 0x21, 0xb9, 0x0d, 0x3d, 0x9e, 0xf9, 0xce, 0xd8,
	0x99, 0x78, 0x71, 0x8f, 0x67, 0xe4, 0x00, 0x6e, 0xa6, 0x59, 0x95, 0x2c, 0xea, 0xc2, 0xef, 0x19,
	0x70, 0x90, 0x66, 0xd5, 0xb7, 0xba, 0x20, 0x47, 0xb0, 0x97, 0x8a, 0x4a, 0x63, 0xa5, 0x13, 0xdd,
	0x48, 0xf4, 0xfb, 0x86, 0x1d, 0xae, 0xb0, 0xd3, 0x46, 0x22, 0x79, 0x08, 0xa0, 0xf8, 0x39, 0x26,
	0xf3, 0x46, 0xa3, 0xf2, 0x77, 0xc6, 0xce, 0xa4, 0x1f, 0x7b, 0x2d, 0x32, 0x6b, 0x01, 0xf2, 0x0c,
	0xf6, 0x45, 0xcd, 0x73, 0x5e, 0xb1, 0x22, 0x39, 0xe3, 0x05, 0x56, 0xac, 0x44, 0xdf, 0x35, 0x36,
	0xa3, 0x8e, 0xf8, 0xb0, 0xc2, 0xc9, 0x6b, 0x80, 0xb4, 0x46, 0xa6, 0x31, 0x4b, 0x98, 0xf6, 0x07,
	0x63, 0x67, 0x32, 0x9c, 0x06, 0xd4, 0xe6, 0xa2, 0x5d, 0x2e, 0x7a, 0xda, 0xe5, 0x8a, 0xbd, 0x95,
	0xfa, 0xad, 0x0e, 0x8f, 0xe0, 0xce, 0x47, 0xd4, 0x26, 0x5e, 0x8c, 0xbf, 0x16, 0xa8, 0xf4, 0x66,
	0xca, 0xf0, 0x15, 0x8c, 0x2e, 0x24, 0x4a, 0x8a, 0x4a, 0x21, 0x79, 0x0c, 0xae, 0xe9, 0xd2, 0xc8,
	0x86, 0xd3, 0x5b, 0xd4, 0x96, 0x49, 0xad, 0xca, 0x72, 0xe1, 0x3b, 0x18, 0x7d, 0xe6, 0xea, 0xaa,
	0xf9, 0x21, 0x78, 0x92, 0xe5, 0x98, 0xb4, 0x49, 0xcd, 0x63, 0x37, 0xde, 0x6d, 0x81, 0x13, 0x7e,
	0x8e, 0x84, 0xc0, 0x4e, 0x7b, 0x36, 0x65, 0xba, 0xb1, 0x39, 0x87, 0x5f, 0x61, 0xff, 0x92, 0xc9,
	0xc5, 0x78, 0xae, 0xb1, 0x54, 0xbe, 0x33, 0xee, 0x6f, 0x19, 0x6f, 0x38, 0x72, 0x0f, 0x5c, 0x2d,
	0x34, 0x2b, 0x56, 0x76, 0xf6, 0x12, 0x3e, 0x01, 0xf2, 0x1e, 0x0b, 0xd4, 0xf8, 0xdf, 0xcc, 0xf7,
	0xe1, 0xee, 0x15, 0x95, 0x9d, 0x3b, 0xfd, 0xeb, 0xc0, 0x9e, 0x41, 0x4e, 0xb0, 0x5e, 0xf2, 0x14,
	0xc9, 0x1b, 0xd8, 0xed, 0xba, 0x21, 0x07, 0xdd, 0x2f, 0x36, 0x0a, 0x0d, 0xfc, 0xeb, 0x84, 0xf5,
	0x0b, 0x6f, 0x90, 0x19, 0x78, 0xeb, 0x78, 0x64, 0x2d, 0xdc, 0xac, 0x2d, 0x78, 0xb0, 0x85, 0x59,
	0x7b, 0x7c, 0x82, 0xe1, 0xa5, 0xcf, 0x92, 0xa0, 0xd3, 0x5e, 0xcf, 0x19, 0x1c, 0x6e, 0xe5, 0x3a,
	0xa7, 0xd9, 0xf3, 0xef, 0x4f, 0x73, 0x41, 0x45, 0xfd, 0x9b, 0x96, 0x18, 0x31, 0x29, 0x55, 0xf4,
	0xa3, 0x91, 0x58, 0xbf, 0x50, 0x4d, 0x95, 0x46, 0xf2, 0x67, 0x6e, 0x97, 0x24, 0xb2, 0xdb, 0x34,
	0x1f, 0x98, 0xdb, 0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0x6c, 0x69, 0xa6, 0x5e, 0x03,
	0x00, 0x00,
}
