// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/v1/media.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Media with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Media) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Media with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MediaMultiError, or nil if none found.
func (m *Media) ValidateAll() error {
	return m.validate(true)
}

func (m *Media) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CdnUrl

	// no validation rules for ContentType

	// no validation rules for SizeBytes

	// no validation rules for OriginalFilename

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MediaValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MediaValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MediaValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MediaMultiError(errors)
	}

	return nil
}

// MediaMultiError is an error wrapping multiple validation errors returned by
// Media.ValidateAll() if the designated constraints aren't met.
type MediaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MediaMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MediaMultiError) AllErrors() []error { return m }

// MediaValidationError is the validation error returned by Media.Validate if
// the designated constraints aren't met.
type MediaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MediaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MediaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MediaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MediaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MediaValidationError) ErrorName() string { return "MediaValidationError" }

// Error satisfies the builtin error interface
func (e MediaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMedia.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MediaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MediaValidationError{}

// Validate checks the field values on GetMediaRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetMediaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMediaRequestMultiError, or nil if none found.
func (m *GetMediaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMediaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetMediaRequestMultiError(errors)
	}

	return nil
}

// GetMediaRequestMultiError is an error wrapping multiple validation errors
// returned by GetMediaRequest.ValidateAll() if the designated constraints
// aren't met.
type GetMediaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMediaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMediaRequestMultiError) AllErrors() []error { return m }

// GetMediaRequestValidationError is the validation error returned by
// GetMediaRequest.Validate if the designated constraints aren't met.
type GetMediaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMediaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMediaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMediaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMediaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMediaRequestValidationError) ErrorName() string { return "GetMediaRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetMediaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMediaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMediaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMediaRequestValidationError{}

// Validate checks the field values on GetMediaResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetMediaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetMediaResponseMultiError, or nil if none found.
func (m *GetMediaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetMediaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetMedia()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetMediaResponseValidationError{
					field:  "Media",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetMediaResponseValidationError{
					field:  "Media",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMedia()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetMediaResponseValidationError{
				field:  "Media",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetMediaResponseMultiError(errors)
	}

	return nil
}

// GetMediaResponseMultiError is an error wrapping multiple validation errors
// returned by GetMediaResponse.ValidateAll() if the designated constraints
// aren't met.
type GetMediaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetMediaResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetMediaResponseMultiError) AllErrors() []error { return m }

// GetMediaResponseValidationError is the validation error returned by
// GetMediaResponse.Validate if the designated constraints aren't met.
type GetMediaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetMediaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetMediaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetMediaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetMediaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetMediaResponseValidationError) ErrorName() string { return "GetMediaResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetMediaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetMediaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetMediaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetMediaResponseValidationError{}

// Validate checks the field values on ListMediaRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMediaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMediaRequestMultiError, or nil if none found.
func (m *ListMediaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMediaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for Page

	if len(errors) > 0 {
		return ListMediaRequestMultiError(errors)
	}

	return nil
}

// ListMediaRequestMultiError is an error wrapping multiple validation errors
// returned by ListMediaRequest.ValidateAll() if the designated constraints
// aren't met.
type ListMediaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMediaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMediaRequestMultiError) AllErrors() []error { return m }

// ListMediaRequestValidationError is the validation error returned by
// ListMediaRequest.Validate if the designated constraints aren't met.
type ListMediaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMediaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMediaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMediaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMediaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMediaRequestValidationError) ErrorName() string { return "ListMediaRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListMediaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMediaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMediaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMediaRequestValidationError{}

// Validate checks the field values on ListMediaResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListMediaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMediaResponseMultiError, or nil if none found.
func (m *ListMediaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMediaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMediaResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMediaResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMediaResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListMediaResponseMultiError(errors)
	}

	return nil
}

// ListMediaResponseMultiError is an error wrapping multiple validation errors
// returned by ListMediaResponse.ValidateAll() if the designated constraints
// aren't met.
type ListMediaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMediaResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMediaResponseMultiError) AllErrors() []error { return m }

// ListMediaResponseValidationError is the validation error returned by
// ListMediaResponse.Validate if the designated constraints aren't met.
type ListMediaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMediaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMediaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMediaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMediaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMediaResponseValidationError) ErrorName() string {
	return "ListMediaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMediaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMediaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMediaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMediaResponseValidationError{}

// Validate checks the field values on DeleteMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMediaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMediaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMediaRequestMultiError, or nil if none found.
func (m *DeleteMediaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMediaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteMediaRequestMultiError(errors)
	}

	return nil
}

// DeleteMediaRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteMediaRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteMediaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMediaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMediaRequestMultiError) AllErrors() []error { return m }

// DeleteMediaRequestValidationError is the validation error returned by
// DeleteMediaRequest.Validate if the designated constraints aren't met.
type DeleteMediaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMediaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMediaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMediaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMediaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMediaRequestValidationError) ErrorName() string {
	return "DeleteMediaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMediaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMediaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMediaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMediaRequestValidationError{}

// Validate checks the field values on DeleteMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteMediaResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteMediaResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteMediaResponseMultiError, or nil if none found.
func (m *DeleteMediaResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteMediaResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteMediaResponseMultiError(errors)
	}

	return nil
}

// DeleteMediaResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteMediaResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteMediaResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteMediaResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteMediaResponseMultiError) AllErrors() []error { return m }

// DeleteMediaResponseValidationError is the validation error returned by
// DeleteMediaResponse.Validate if the designated constraints aren't met.
type DeleteMediaResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteMediaResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteMediaResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteMediaResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteMediaResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteMediaResponseValidationError) ErrorName() string {
	return "DeleteMediaResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteMediaResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteMediaResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteMediaResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteMediaResponseValidationError{}
