// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: api/v1/post.proto

package v1

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =====================
// PostService Interface
// =====================

type PostService interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)

	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)

	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)

	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)

	PublishPost(context.Context, *PublishPostRequest) (*PublishPostResponse, error)

	DeletePost(context.Context, *DeletePostRequest) (*DeletePostResponse, error)
}

// ===========================
// PostService Protobuf Client
// ===========================

type postServiceProtobufClient struct {
	client      HTTPClient
	urls        [6]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewPostServiceProtobufClient creates a Protobuf client that implements the PostService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPostServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) PostService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "api.v1", "PostService")
	urls := [6]string{
		serviceURL + "CreatePost",
		serviceURL + "GetPost",
		serviceURL + "ListPosts",
		serviceURL + "UpdatePost",
		serviceURL + "PublishPost",
		serviceURL + "DeletePost",
	}

	return &postServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *postServiceProtobufClient) CreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	caller := c.callCreatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return c.callCreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceProtobufClient) callCreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceProtobufClient) GetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	caller := c.callGetPost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return c.callGetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceProtobufClient) callGetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceProtobufClient) ListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	caller := c.callListPosts
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return c.callListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceProtobufClient) callListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceProtobufClient) UpdatePost(ctx context.Context, in *UpdatePostRequest) (*UpdatePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePost")
	caller := c.callUpdatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePostRequest) when calling interceptor")
					}
					return c.callUpdatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceProtobufClient) callUpdatePost(ctx context.Context, in *UpdatePostRequest) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceProtobufClient) PublishPost(ctx context.Context, in *PublishPostRequest) (*PublishPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "PublishPost")
	caller := c.callPublishPost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *PublishPostRequest) (*PublishPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PublishPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PublishPostRequest) when calling interceptor")
					}
					return c.callPublishPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PublishPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PublishPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceProtobufClient) callPublishPost(ctx context.Context, in *PublishPostRequest) (*PublishPostResponse, error) {
	out := new(PublishPostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceProtobufClient) DeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	caller := c.callDeletePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return c.callDeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceProtobufClient) callDeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =======================
// PostService JSON Client
// =======================

type postServiceJSONClient struct {
	client      HTTPClient
	urls        [6]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewPostServiceJSONClient creates a JSON client that implements the PostService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPostServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) PostService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "api.v1", "PostService")
	urls := [6]string{
		serviceURL + "CreatePost",
		serviceURL + "GetPost",
		serviceURL + "ListPosts",
		serviceURL + "UpdatePost",
		serviceURL + "PublishPost",
		serviceURL + "DeletePost",
	}

	return &postServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *postServiceJSONClient) CreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	caller := c.callCreatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return c.callCreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceJSONClient) callCreatePost(ctx context.Context, in *CreatePostRequest) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceJSONClient) GetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	caller := c.callGetPost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return c.callGetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceJSONClient) callGetPost(ctx context.Context, in *GetPostRequest) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceJSONClient) ListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	caller := c.callListPosts
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return c.callListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceJSONClient) callListPosts(ctx context.Context, in *ListPostsRequest) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceJSONClient) UpdatePost(ctx context.Context, in *UpdatePostRequest) (*UpdatePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePost")
	caller := c.callUpdatePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePostRequest) when calling interceptor")
					}
					return c.callUpdatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceJSONClient) callUpdatePost(ctx context.Context, in *UpdatePostRequest) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceJSONClient) PublishPost(ctx context.Context, in *PublishPostRequest) (*PublishPostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "PublishPost")
	caller := c.callPublishPost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *PublishPostRequest) (*PublishPostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PublishPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PublishPostRequest) when calling interceptor")
					}
					return c.callPublishPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PublishPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PublishPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceJSONClient) callPublishPost(ctx context.Context, in *PublishPostRequest) (*PublishPostResponse, error) {
	out := new(PublishPostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postServiceJSONClient) DeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	caller := c.callDeletePost
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return c.callDeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postServiceJSONClient) callDeletePost(ctx context.Context, in *DeletePostRequest) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==========================
// PostService Server Handler
// ==========================

type postServiceServer struct {
	PostService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewPostServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewPostServiceServer(svc PostService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &postServiceServer{
		PostService:      svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *postServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *postServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// PostServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const PostServicePathPrefix = "/twirp/api.v1.PostService/"

func (s *postServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "api.v1")
	ctx = ctxsetters.WithServiceName(ctx, "PostService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "api.v1.PostService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreatePost":
		s.serveCreatePost(ctx, resp, req)
		return
	case "GetPost":
		s.serveGetPost(ctx, resp, req)
		return
	case "ListPosts":
		s.serveListPosts(ctx, resp, req)
		return
	case "UpdatePost":
		s.serveUpdatePost(ctx, resp, req)
		return
	case "PublishPost":
		s.servePublishPost(ctx, resp, req)
		return
	case "DeletePost":
		s.serveDeletePost(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *postServiceServer) serveCreatePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreatePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreatePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postServiceServer) serveCreatePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreatePostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PostService.CreatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return s.PostService.CreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreatePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreatePostResponse and nil error while calling CreatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveCreatePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreatePostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PostService.CreatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreatePostRequest) when calling interceptor")
					}
					return s.PostService.CreatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*CreatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*CreatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *CreatePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreatePostResponse and nil error while calling CreatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveGetPost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetPostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetPostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postServiceServer) serveGetPostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetPostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PostService.GetPost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return s.PostService.GetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPostResponse and nil error while calling GetPost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveGetPostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetPostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PostService.GetPost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPostRequest) when calling interceptor")
					}
					return s.PostService.GetPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPostResponse and nil error while calling GetPost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveListPosts(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListPostsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListPostsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postServiceServer) serveListPostsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListPostsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PostService.ListPosts
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return s.PostService.ListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListPostsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListPostsResponse and nil error while calling ListPosts. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveListPostsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListPosts")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListPostsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PostService.ListPosts
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListPostsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListPostsRequest) when calling interceptor")
					}
					return s.PostService.ListPosts(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListPostsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListPostsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListPostsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListPostsResponse and nil error while calling ListPosts. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveUpdatePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdatePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdatePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postServiceServer) serveUpdatePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdatePostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PostService.UpdatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePostRequest) when calling interceptor")
					}
					return s.PostService.UpdatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdatePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdatePostResponse and nil error while calling UpdatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveUpdatePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdatePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdatePostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PostService.UpdatePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdatePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdatePostRequest) when calling interceptor")
					}
					return s.PostService.UpdatePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*UpdatePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*UpdatePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *UpdatePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *UpdatePostResponse and nil error while calling UpdatePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) servePublishPost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.servePublishPostJSON(ctx, resp, req)
	case "application/protobuf":
		s.servePublishPostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postServiceServer) servePublishPostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PublishPost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(PublishPostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PostService.PublishPost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *PublishPostRequest) (*PublishPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PublishPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PublishPostRequest) when calling interceptor")
					}
					return s.PostService.PublishPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PublishPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PublishPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *PublishPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PublishPostResponse and nil error while calling PublishPost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) servePublishPostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "PublishPost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(PublishPostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PostService.PublishPost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *PublishPostRequest) (*PublishPostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PublishPostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PublishPostRequest) when calling interceptor")
					}
					return s.PostService.PublishPost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PublishPostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PublishPostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *PublishPostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PublishPostResponse and nil error while calling PublishPost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveDeletePost(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeletePostJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeletePostProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postServiceServer) serveDeletePostJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeletePostRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.PostService.DeletePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return s.PostService.DeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeletePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeletePostResponse and nil error while calling DeletePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) serveDeletePostProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePost")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeletePostRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.PostService.DeletePost
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeletePostRequest) (*DeletePostResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePostRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePostRequest) when calling interceptor")
					}
					return s.PostService.DeletePost(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*DeletePostResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*DeletePostResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *DeletePostResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeletePostResponse and nil error while calling DeletePost. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor2, 0
}

func (s *postServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *postServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "api.v1", "PostService")
}

var twirpFileDescriptor2 = []byte{
	// 793 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x41, 0x4f, 0xf3, 0x46,
	0x10, 0xc5, 0x71, 0x9c, 0xc4, 0xe3, 0x4f, 0x1f, 0x64, 0x8b, 0xc0, 0x18, 0xa9, 0x04, 0xb7, 0x87,
	0xa8, 0x2a, 0xb6, 0x08, 0x52, 0x69, 0xab, 0x5e, 0x80, 0xa2, 0x16, 0xa9, 0x48, 0xc8, 0xd0, 0x4b,
	0x39, 0x58, 0x8e, 0xbd, 0x84, 0x15, 0x49, 0xec, 0x7a, 0xd7, 0x51, 0xc3, 0xb1, 0xff, 0xa3, 0xc7,
	0x5e, 0xfb, 0x43, 0xfa, 0xab, 0xaa, 0xdd, 0xb5, 0x63, 0x13, 0x87, 0x80, 0xd4, 0xef, 0xb6, 0xfb,
	0xe6, 0xcd, 0x78, 0x66, 0xde, 0xb3, 0x65, 0xe8, 0x06, 0x09, 0x71, 0x67, 0xc7, 0x6e, 0x12, 0x53,
	0xe6, 0x24, 0x69, 0xcc, 0x62, 0xd4, 0x0a, 0x12, 0xe2, 0xcc, 0x8e, 0xad, 0x83, 0x51, 0x1c, 0x8f,
	0xc6, 0xd8, 0x15, 0xe8, 0x30, 0x7b, 0x70, 0x19, 0x99, 0x60, 0xca, 0x82, 0x49, 0x22, 0x89, 0xf6,
	0xbf, 0x2a, 0x34, 0x6f, 0x62, 0xca, 0xd0, 0x47, 0x68, 0x90, 0xc8, 0x54, 0x7a, 0x4a, 0x5f, 0xf7,
	0x1a, 0x24, 0x42, 0x26, 0xb4, 0xc3, 0x78, 0xca, 0xf0, 0x94, 0x99, 0x0d, 0x01, 0x16, 0x57, 0xf4,
	0x39, 0xc0, 0x8c, 0x50, 0x32, 0x24, 0x63, 0xc2, 0xe6, 0xa6, 0x2a, 0x82, 0x15, 0x04, 0xed, 0x40,
	0x8b, 0xb2, 0x80, 0x65, 0xd4, 0x6c, 0x8a, 0x58, 0x7e, 0x43, 0xfb, 0xa0, 0x4f, 0x70, 0x44, 0x02,
	0x9f, 0x44, 0xd4, 0xd4, 0x7a, 0x6a, 0x5f, 0xf7, 0x3a, 0x02, 0xb8, 0x8a, 0x28, 0x3a, 0x84, 0x0f,
	0x74, 0x3e, 0x0d, 0x7d, 0x16, 0xa4, 0x23, 0xcc, 0xa8, 0xd9, 0x12, 0x71, 0x83, 0x63, 0x77, 0x12,
	0x42, 0xd7, 0xd0, 0x0d, 0xd3, 0x98, 0x52, 0x9f, 0xcf, 0xe9, 0xe7, 0x8f, 0x68, 0xf7, 0xd4, 0xbe,
	0x31, 0x38, 0x74, 0xe4, 0xbc, 0x0e, 0x1f, 0xc5, 0xb9, 0xe0, 0x2c, 0x7e, 0xba, 0x15, 0x9c, 0xcb,
	0x29, 0x4b, 0xe7, 0xde, 0x66, 0xf8, 0x12, 0x45, 0xdf, 0x01, 0x84, 0x29, 0x0e, 0x18, 0x8e, 0xfc,
	0x80, 0x99, 0x9d, 0x9e, 0xd2, 0x37, 0x06, 0x96, 0x23, 0xf7, 0xe5, 0x14, 0xfb, 0x72, 0xee, 0x8a,
	0x7d, 0x79, 0x7a, 0xce, 0x3e, 0x63, 0x3c, 0x35, 0x4b, 0xa2, 0x22, 0x55, 0x7f, 0x3b, 0x35, 0x67,
	0x9f, 0x31, 0xeb, 0x1e, 0xb6, 0x57, 0xb5, 0x87, 0xb6, 0x40, 0x7d, 0xc2, 0xf3, 0x7c, 0xff, 0xfc,
	0x88, 0x8e, 0x40, 0x9b, 0x05, 0xe3, 0x0c, 0x8b, 0xf5, 0x1b, 0x83, 0xdd, 0x62, 0xc4, 0xa5, 0x74,
	0x4f, 0xb2, 0xbe, 0x6f, 0x7c, 0xab, 0xd8, 0x7f, 0x36, 0x60, 0x73, 0x29, 0xcc, 0x75, 0xa4, 0x59,
	0x18, 0x62, 0x4a, 0x45, 0xf1, 0x8e, 0x57, 0x5c, 0xd1, 0x36, 0x68, 0x38, 0x4d, 0xe3, 0x34, 0xd7,
	0x57, 0x5e, 0xd0, 0x01, 0x18, 0xc9, 0x38, 0x60, 0x0f, 0x71, 0x3a, 0xf1, 0x49, 0x54, 0xc8, 0x5b,
	0x40, 0x57, 0x11, 0x3a, 0x05, 0x9d, 0x0b, 0x20, 0x67, 0x6f, 0xbe, 0x39, 0x7b, 0x47, 0x92, 0xcf,
	0x18, 0xaf, 0x9c, 0x62, 0x96, 0xce, 0xfd, 0x30, 0xce, 0xa6, 0xcc, 0xd4, 0x7a, 0x4a, 0x5f, 0xf3,
	0x40, 0x40, 0x17, 0x1c, 0xe1, 0x1e, 0x98, 0x62, 0x1c, 0x51, 0x5f, 0xae, 0xcb, 0x6c, 0x89, 0x7e,
	0x0d, 0x81, 0xfd, 0x2a, 0xa0, 0x92, 0x12, 0xe1, 0x31, 0x66, 0xd8, 0x6c, 0x57, 0x28, 0x3f, 0x0a,
	0xc8, 0xfe, 0x5b, 0x81, 0xee, 0x85, 0x90, 0x8a, 0x6f, 0xc1, 0xc3, 0xbf, 0x67, 0x98, 0xb2, 0xaa,
	0x9d, 0x95, 0x75, 0x76, 0x6e, 0xac, 0xb1, 0xb3, 0xfa, 0xba, 0x9d, 0x9b, 0x6f, 0xd8, 0x59, 0xab,
	0xd9, 0xd9, 0xfe, 0x06, 0x50, 0xb5, 0x4d, 0x9a, 0xc4, 0x53, 0x8a, 0x51, 0x0f, 0x9a, 0x7c, 0x61,
	0xa2, 0x49, 0x63, 0xf0, 0xa1, 0xea, 0x6b, 0x4f, 0x44, 0xec, 0x1e, 0x7c, 0xfc, 0x09, 0xb3, 0xea,
	0x6c, 0x4b, 0xaf, 0xae, 0x7d, 0x02, 0x9b, 0x0b, 0xc6, 0xbb, 0xcb, 0xde, 0xc3, 0xd6, 0x2f, 0x84,
	0x8a, 0x2c, 0x5a, 0x14, 0xde, 0x07, 0x3d, 0x09, 0x46, 0xd8, 0xa7, 0xe4, 0x19, 0x8b, 0x54, 0xcd,
	0xeb, 0x70, 0xe0, 0x96, 0x3c, 0x63, 0x84, 0xa0, 0xc9, 0xcf, 0x62, 0x63, 0x9a, 0x27, 0xce, 0xaf,
	0xed, 0xca, 0xbe, 0x86, 0x6e, 0xa5, 0x78, 0xde, 0x93, 0x0d, 0x1a, 0x7f, 0x32, 0xf7, 0xa5, 0x5a,
	0x6b, 0x4a, 0x86, 0xb8, 0x47, 0x59, 0xcc, 0x82, 0x71, 0xfe, 0x14, 0x79, 0xb1, 0xff, 0x52, 0xa0,
	0x2b, 0x0d, 0xb1, 0x66, 0x0d, 0xff, 0xe3, 0x0b, 0xf6, 0x09, 0xa4, 0xad, 0xb6, 0xf7, 0x6e, 0x0d,
	0xbe, 0x04, 0x74, 0x93, 0x0d, 0xc7, 0x84, 0x3e, 0xae, 0x93, 0xf7, 0x14, 0x3e, 0x7b, 0xc1, 0x7a,
	0x77, 0xf9, 0x2f, 0xa0, 0x2b, 0xdf, 0x91, 0x75, 0xd5, 0xb7, 0x01, 0x55, 0x49, 0xb2, 0xf8, 0xe0,
	0x1f, 0x15, 0x0c, 0xf1, 0x51, 0xc1, 0xe9, 0x8c, 0x84, 0x18, 0x5d, 0x02, 0x94, 0xe6, 0x45, 0x7b,
	0xe5, 0xb7, 0x69, 0xe9, 0xbd, 0xb3, 0xac, 0x55, 0x21, 0x59, 0xd4, 0xde, 0x40, 0x3f, 0x40, 0x3b,
	0x77, 0x2a, 0xda, 0x29, 0x88, 0x2f, 0xcd, 0x6d, 0xed, 0xd6, 0xf0, 0x45, 0xf6, 0x39, 0xe8, 0x0b,
	0x57, 0x21, 0xb3, 0xe0, 0x2d, 0xbb, 0xd8, 0xda, 0x5b, 0x11, 0x59, 0xd4, 0xb8, 0x04, 0x28, 0xa5,
	0x2a, 0x07, 0xa9, 0xb9, 0xab, 0x1c, 0xa4, 0xae, 0xac, 0xbd, 0x81, 0x7e, 0x06, 0xa3, 0xa2, 0x09,
	0x5a, 0x90, 0xeb, 0x72, 0x5a, 0xfb, 0x2b, 0x63, 0xd5, 0x86, 0xca, 0xfd, 0x97, 0x0d, 0xd5, 0x84,
	0x2b, 0x1b, 0xaa, 0xcb, 0x65, 0x6f, 0x9c, 0x7f, 0xfd, 0xdb, 0x57, 0xa3, 0xd8, 0x89, 0xd3, 0x3f,
	0x9c, 0x09, 0x76, 0x83, 0x24, 0xa1, 0xee, 0xe3, 0x3c, 0xc1, 0xe9, 0x11, 0xb7, 0xa9, 0x9b, 0x3c,
	0x8d, 0xe4, 0x1f, 0x81, 0x2b, 0xff, 0x1c, 0x86, 0x2d, 0x71, 0x3b, 0xf9, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x86, 0xc3, 0x89, 0x9c, 0x4a, 0x08, 0x00, 0x00,
}
